### ISSUE TITLE
dns error

### ISSUE THREAD

**Issue by snizzleorg** [patrickbusch/homebridge-docker#13]
unfortunately I cannot get it to run - I always get dos error. Anahi is running outside of the container. And I purged the persist folder as well...

any ideas?

```
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/advertisement.js:56
  dns_sd.DNSServiceRegister(self.serviceRef, flags, ifaceIdx, name,
         ^
Error: dns service error: unknown
    at Error (native)
    at new Advertisement (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/advertisement.js:64:10)
    at Advertiser.startAdvertising (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Advertiser.js:43:30)
    at Bridge.Accessory._onListening (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:510:20)
    at HAPServer.emit (events.js:104:17)
    at HAPServer._onListening (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:182:8)
    at EventedHTTPServer.emit (events.js:104:17)
    at EventedHTTPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:62:10)
    at Server.emit (events.js:104:17)

```

**Comment by timoschilling** [comment]
I have the same problem

**Comment by gazzer82** [comment]
Did you manage to resolve this, same issue here?

**Comment by snizzleorg** [comment]
No I did not and gave up. I now run it directly on the host. less then ideal but it works without any problems

**Comment by felixbouleau** [comment]
@gazzer82 @timoschilling @snizzleorg Have a look at #15 which solved the issue for me.
