### ISSUE TITLE
Issues with docker build on raspberry pi

### ISSUE THREAD

**Issue by jritsema** [patrickbusch/homebridge-docker#17]
Fyi...just tried out your project on raspberry pi and got the following error after running the built docker image...

```
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
sed: can't read /etc/avahi/avahi-daemon.conf: No such file or directory
/root/run.sh: line 5: dbus-daemon: command not found
/root/run.sh: line 6: avahi-daemon: command not found
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Camera.js:28
  let options = {
  ^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/index.js:3:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

...looks like the Dockerfile is installing an older version of nodejs.

**Comment by mverzakov** [comment]
Have the same issue.

**Comment by jritsema** [comment]
Hey @mverzakov I ended up making my own raspberry pi / arm-specific version in case it helps.

https://github.com/jritsema/rpi-homebridge

**Comment by mverzakov** [comment]
Wow! @jritsema, Thanks! It works amazing. Now I can switch off the lights by asking Siri!
